-- CreateEnum
CREATE TYPE "VENDOR_TYPE" AS ENUM ('DEFAULT', 'CHIT_FUND_COMPANY', 'LOAD_BORROWER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "vendorType" "VENDOR_TYPE" NOT NULL DEFAULT 'DEFAULT';
